"""Profile the legacy sheet exports before writing a single line of importer.

Reads the CSVs with a real RFC4180 parser (fields contain embedded newlines,
so `wc -l` lies), and reports per column: fill rate, cardinality, the actual
value distribution for anything low-cardinality, and format checks for the
columns the import depends on.

Writes docs/source-profile.md. Read-only; touches nothing.

    python scripts/profile_sheets.py
"""
import csv, io, os, re, sys
from collections import Counter, OrderedDict

csv.field_size_limit(10_000_000)

SHEETS = "data/incoming/sheets"
OUT = "docs/source-profile.md"

FILES = {
    "Consultation Record": "NEW SALES TEAM WORKING DOC 2026 - July - Consultation Record - AP+TA+SS.csv",
    "Medicine Order Record": "NEW SALES TEAM WORKING DOC 2026 - July - Medicine Order Record - AP+TA+S.csv",
}

BLANK = {"", "-", "--", "n/a", "N/A", "na", "NA", "null", "NULL", "#N/A", "TBD"}

PHONE_OK = re.compile(r"^[6-9]\d{9}$")
PIN_OK = re.compile(r"^[1-9]\d{5}$")
MONEY_OK = re.compile(r"^\s*₹?\s*[\d,]+(\.\d+)?\s*$")

# Values that must never appear in these columns — the tell for a column shift.
SHIFT_TELLS = {"Follow up", "Follow Up", "follow up", "Followup"}


def norm_phone(v):
    d = re.sub(r"\D", "", v or "")
    if len(d) > 10:
        d = d[-10:]
    return d if PHONE_OK.match(d) else None


def load(path):
    with io.open(path, encoding="utf-8-sig", newline="") as f:
        rows = list(csv.reader(f))
    header = [h.strip() for h in rows[0]]
    body = [r for r in rows[1:] if any((c or "").strip() for c in r)]
    return header, body


def val(row, i):
    return (row[i] if i < len(row) else "").strip()


def profile(name, path, out):
    header, body = load(path)
    out.append(f"\n## {name}\n")
    out.append(f"`{os.path.basename(path)}`\n")
    out.append(f"- **{len(body)} data rows**, {len(header)} columns")
    ragged = Counter(len(r) for r in body)
    if len(ragged) > 1:
        out.append(f"- ⚠️ **ragged rows** — column counts seen: "
                   + ", ".join(f"{k} cols x{v}" for k, v in sorted(ragged.items())))
    out.append("")
    out.append("| # | column | filled | distinct | notes |")
    out.append("|---|---|---|---|---|")

    details = []
    for i, col in enumerate(header):
        vals = [val(r, i) for r in body]
        nonblank = [v for v in vals if v and v not in BLANK]
        distinct = Counter(nonblank)
        pct = round(100 * len(nonblank) / max(len(body), 1))
        note = ""

        low = col.lower()
        if "number" in low or "contact" in low:
            bad = [v for v in nonblank if not norm_phone(v)]
            note = f"**{len(nonblank)-len(bad)} valid**, {len(bad)} unparseable" if nonblank else ""
        elif "pincode" in low:
            bad = [v for v in nonblank if not PIN_OK.match(re.sub(r"\D", "", v))]
            note = f"{len(bad)} invalid" if bad else "all valid"
        elif "amount" in low or "value" in low or "charge" in low or low == "discount":
            bad = [v for v in nonblank if not MONEY_OK.match(v)]
            note = f"⚠️ **{len(bad)} non-numeric**" if bad else "all numeric"

        hits = [v for v in nonblank if v in SHIFT_TELLS]
        if hits:
            note += f" · 🚨 **{len(hits)} rows contain 'Follow up'**"

        out.append(f"| {i} | {col} | {pct}% | {len(distinct)} | {note} |")

        if 0 < len(distinct) <= 25:
            details.append((col, distinct, len(nonblank)))

    out.append("")
    out.append(f"### {name} — value distributions (low-cardinality columns)\n")
    for col, dist, total in details:
        top = ", ".join(f"`{k}` ×{v}" for k, v in dist.most_common(25))
        out.append(f"- **{col}** ({total} filled): {top}")
    return header, body


def main():
    out = ["# source-profile.md", "",
           "Generated by `python scripts/profile_sheets.py`. Read-only profiling of the legacy",
           "sheet exports, done before writing the importer so the mapping is based on what the",
           "files actually contain rather than on what the column names suggest.", ""]

    data = {}
    for name, fn in FILES.items():
        p = os.path.join(SHEETS, fn)
        if not os.path.exists(p):
            out.append(f"\n## {name}\n\n_missing: {p}_")
            continue
        data[name] = profile(name, p, out)

    # ---- cross-file checks -------------------------------------------------
    out.append("\n---\n\n## Cross-checks against PROJECT.md reference numbers\n")

    if "Consultation Record" in data:
        h, b = data["Consultation Record"]
        idx = {c: i for i, c in enumerate(h)}
        st = Counter(val(r, idx["Consultation Status"]) for r in b)
        out.append(f"- Consultation rows in file: **{len(b)}** (PROJECT.md says 507 for July)")
        for k, v in st.most_common():
            out.append(f"  - `{k or '(blank)'}` × {v}")

    if "Medicine Order Record" in data:
        h, b = data["Medicine Order Record"]
        idx = {c: i for i, c in enumerate(h)}
        out.append(f"- Order rows in file: **{len(b)}** (PROJECT.md says 163 for July)")
        for col, label in [("Payment Mode", "Payment mode"),
                           ("Shipped By", "Courier"),
                           ("Course Duration", "Course duration"),
                           ("Order Type", "Order type")]:
            if col in idx:
                d = Counter(val(r, idx[col]) for r in b if val(r, idx[col]))
                out.append(f"  - **{label}**: " + ", ".join(f"`{k}` ×{v}" for k, v in d.most_common(15)))

    io.open(OUT, "w", encoding="utf-8").write("\n".join(out))
    print(f"wrote {OUT}")
    for name, (h, b) in data.items():
        print(f"  {name}: {len(b)} rows, {len(h)} columns")


if __name__ == "__main__":
    main()
